<?php

namespace Database\Factories;

use App\Models\Category;
use App\Models\CategoryModel;
use App\Models\Products;
use App\Models\Suppliers;
use App\Models\Unit;
use Illuminate\Database\Eloquent\Factories\Factory;

class ProductsFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Products::class;

    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        $petProducts = [
            "Premium Dog Food - Chicken Flavor",
            "Grain-Free Cat Food - Salmon",
            "Dental Chews for Dogs",
            "Catnip Toys",
            "Flea and Tick Prevention for Dogs",
            "Heartworm Medication for Cats",
            "Pet Bed - Small",
            "Pet Carrier - Medium",
            "Leather Collar for Dogs",
            "Retractable Leash",
            "Automatic Feeder",
            "Water Fountain for Pets",
            "Grooming Kit for Long-Haired Cats",
            "Shorthair Brush for Dogs",
            "Bird Cage - Large",
            "Fish Tank Starter Kit",
            "Hammock Bed for Ferrets",
            "Rabbit Hutch",
            "Guinea Pig Playpen",
            "Hamster Wheel",
            "Reptile Heat Lamp",
            "Turtle Tank Filter",
            "Snake Hide Box",
            "Iguana UV Light",
            "Parrot Perch",
            "Bird Seed Mix",
            "Mealworms for Reptiles",
            "Cricket Feeder",
            "Hermit Crab Shells",
            "Aquarium Plants",
            "Fish Flakes",
            "Goldfish Pellets",
            "Beta Fish Food",
            "Tropical Fish Gravel",
            "Air Pump for Aquarium",
            "Water Conditioner",
            "Ammonia Test Kit",
            "pH Test Strips",
            "Digital Thermometer for Aquarium",
            "Submersible Heater",
            "Protein Skimmer for Saltwater Tanks",
            "Live Rock for Marine Aquariums",
            "Saltwater Test Kit",
            "Algae Wafers for Bottom Feeders",
            "Bloodworms for Tropical Fish",
            "Brine Shrimp Eggs",
            "Dog Training Pads",
            "Odor Eliminator Spray",
            "Stain Remover for Carpets",
            "Pet Hair Vacuum",
            "Lint Roller for Clothes",
            "Portable Pet Water Bottle",
            "Cooling Mat for Dogs",
            "Heated Pet Bed",
            "Reflective Vest for Night Walks",
            "GPS Tracker for Pets",
            "Microchip Scanner",
            "Pet First Aid Kit",
            "Calming Spray for Cats",
            "Thunder Jacket for Dogs",
            "Interactive Puzzle Toy",
            "Slow Feeder Bowl",
            "No-Spill Water Bowl",
            "Elevated Pet Diner",
            "Orthopedic Pet Bed",
            "Warming Disc for Kittens",
            "Nesting Material for Small Animals",
            "Exercise Ball for Birds",
            "Perch Stand for Parrots",
            "Climbing Tree for Cats",
            "Window Sill Perch",
            "Scratching Post",
            "Litter Box Enclosure",
            "Self-Cleaning Litter Box",
            "Clumping Cat Litter",
            "Biodegradable Dog Waste Bags",
            "Poop Scooper",
            "Waste Disposal System",
            "Urine Odor Neutralizer",
            "Ear Cleaning Solution",
            "Eye Cleaning Wipes",
            "Nail Trimmer with Guard",
            "Pet Toothbrush and Toothpaste",
            "Joint Supplement for Senior Pets",
            "Multivitamin for Dogs",
            "Omega Fatty Acid Supplement",
            "Probiotics for Digestive Health",
            "Hypoallergenic Shampoo",
            "Conditioner for Dry Skin",
            "Fur Detangler Spray",
            "Deodorizing Spray for Pets",
            "Dry Shampoo for Dogs",
            "Gentle Puppy Shampoo",
            "Natural Flea Repellent",
            "Tick Removal Tool",
            "Pet Sunscreen",
            "Insect Repellent Bandana",
            "Travel Crate for Airline Use",
            "Car Seat Cover for Pets",
            "Booster Seat for Small Dogs",
            "Seat Belt Restraint",
            "Life Jacket for Swimming Dogs",
            "Floating Toys for Pool Fun",
            "Snuggle Bed for Kittens",
            "Cuddle Cave for Cats",
            "Thermal Pet Mat",
            "Outdoor Kennel",
            "Indoor Pen for Puppies",
            "Play Tunnel for Cats",
            "Hide and Seek Toy",
            "Squeaky Plush Toys",
            "Rope Tug Toy",
            "Ball Launcher for Dogs",
            "Frictionless Door Protector",
            "Baby Gate for Stairs",
            "Room Divider",
            "Pet Steps for High Beds",
            "Stroller for Small Pets",
            "Backpack Carrier for Hiking",
            "Rolling Travel Bag",
            "Insulated Food Container",
            "Silicone Feeding Mat",
            "Non-Tip Bowl Set",
            "Bottle Brush Cleaner",
            "Pet Grooming Glove",
            "Double-Sided Comb",
            "Pin Brush for Dogs",
            "Slicker Brush for Cats",
            "Dematting Tool",
            "Undercoat Rake",
            "Furminator Deshedding Tool",
            "Electric Nail Grinder",
            "Pet Nail Clipper",
            "Styptic Powder",
            "Grooming Scissors",
            "Round-Tip Scissors",
            "Curved Scissors for Face",
            "Thin Strap Collar",
            "Martingale Collar",
            "Chain Collar",
            "Breakaway Collar for Cats",
            "LED Collar for Visibility",
            "Personalized ID Tags",
            "Engraved Name Tag",
            "Blunt-Tip Leash",
            "Chain Leash",
            "Nylon Leash",
            "Biothane Leash",
            "Harness for Easy Walking",
            "Step-In Harness",
            "Front-Clip Harness",
            "Back-Clip Harness",
            "No-Pull Harness",
            "Head Halter for Dogs",
            "Muzzle for Safe Handling",
            "Training Clicker",
            "Treat Pouch",
            "Whistle for Recall",
            "Flirt Pole for Exercise",
            "Agility Tunnel",
            "Weave Poles",
            "Jump Bar",
            "Teeter Totter",
            "Pause Table",
            "A-Frame",
            "Dog Ramp",
            "Pet Stairs",
            "Ladder for Agility",
            "Balance Beam",
            "Hoops for Jumping",
            "Plastic Tunnel",
            "Soft Crates",
            "Wire Crates",
            "Plush Crates",
            "Foldable Crates",
            "Heavy-Duty Crates",
            "Crate Pad",
            "Crate Cover",
            "Kennel End Table",
            "Wooden Dog House",
            "Plastic Dog House",
            "Insulated Dog House",
            "Heated Dog Bed",
            "Cooling Dog Bed",
            "Memory Foam Dog Bed",
            "Donut Bed for Dogs",
            "Cuddle Cup Bed",
            "Bolster Bed for Cats",
            "Cat Condo",
            "Cat Tree",
            "Wall-Mounted Shelves",
            "Cat Window Perch",
            "Cardboard Scratch Pad",
            "Vertical Scratcher",
            "Horizontal Scratcher",
            "Corrugated Scratcher",
            "Sisal Rope Scratcher",
            "Carpet Scratcher",
            "Wave Scratcher",
            "Litter Scoop",
            "Litter Genie Refills",
            "Litter Box Liners",
            "Disposable Litter Boxes",
            "Corner Litter Box",
            "Top Entry Litter Box",
            "Covered Litter Box",
            "High Sided Litter Box",
            "Extra-Large Litter Box",
            "Litter Attractant",
            "Litter Deodorizer",
            "Activated Carbon Filters",
            "Charcoal Filters",
            "Replacement Filters",
            "Air Purifier for Pet Odors",
            "Ultrasonic Pest Repeller",
            "Electronic Mouse Trap",
            "Humane Live Animal Trap",
            "Rodent Bait Station",
            "Insect Trap",
            "Fly Trap",
            "Mosquito Netting",
            "Bug Zapper",
            "Ant Killer",
            "Spider Catcher",
            "Ladybug House",
            "Butterfly Feeder",
            "Hummingbird Feeder",
            "Birdbath",
            "Birdhouse",
            "Bat House",
            "Owl Box",
            "Squirrel Proof Bird Feeder",
            "Wildlife Camera",
            "Motion Sensor Sprinkler",
            "Solar Powered Animal Repeller",
            "Ultrasonic Animal Repeller",
            "Animal Repellent Granules",
            "Liquid Fence",
            "Plant Repellent",
            "Tree Wrap",
            "Critter Pricker",
            "Garden Netting",
            "Hardware Cloth",
            "Chicken Wire",
            "Rabbit Fence",
            "Deer Fence",
            "Gopher Trap",
            "Mole Trap",
            "Vole Bait",
            "Snake Repellent",
            "Fox Urine",
            "Coyote Urine",
            "Skunk Repellent",
            "Raccoon Repellent",
            "Squirrel Repellent",
            "Chipmunk Repellent",
            "Groundhog Repellent",
            "Possum Repellent",
            "Armadillo Repellent",
            "Porcupine Repellent",
            "Badger Repellent",
            "Bobcat Repellent",
            "Mountain Lion Repellent",
            "Bear Repellent",
            "Wolf Repellent",
            "Peacock Repellent",
            "Turkey Repellent",
            "Geese Repellent",
            "Duck Repellent",
            "Swan Repellent",
            "Seagull Repellent",
            "Crow Repellent",
            "Magpie Repellent",
            "Starling Repellent",
            "Pigeon Repellent",
            "Sparrow Repellent",
            "Finch Repellent",
            "Bluejay Repellent",
            "Mockingbird Repellent",
            "Robin Repellent",
            "Cardinal Repellent",
            "Woodpecker Repellent",
            "Hawk Repellent",
            "Owl Repellent",
            "Eagle Repellent",
            "Falcon Repellent",
            "Buzzard Repellent",
            "Vulture Repellent",
            "Condor Repellent",
            "Osprey Repellent",
            "Harrier Repellent",
            "Kestrel Repellent",
            "Merlin Repellent",
            "Peregrine Repellent",
            "Sparrowhawk Repellent",
            "Goshawk Repellent",
            "Redtail Repellent",
            "Coopers Hawk Repellent",
            "Sharp-Shinned Hawk Repellent",
            "Northern Harrier Repellent",
            "Broad-Winged Hawk Repellent",
            "Swainsons Hawk Repellent",
            "Red-Shouldered Hawk Repellent",
            "Zone-Tailed Hawk Repellent",
            "Short-Tailed Hawk Repellent",
            "Long-Tailed Hawk Repellent",
            "Ferruginous Hawk Repellent",
            "Rough-Legged Hawk Repellent",
            "Golden Eagle Repellent",
            "Bald Eagle Repellent",
            "White-Tailed Eagle Repellent",
            "Stellers Sea Eagle Repellent",
            "Harpy Eagle Repellent",
            "Philippine Eagle Repellent",
            "Andean Condor Repellent",
            "California Condor Repellent",
            "King Vulture Repellent",
            "Black Vulture Repellent",
            "Turkey Vulture Repellent",
        ];
        return [
            'product_name' => $this->faker->randomElement($petProducts),
            'product_category' => Category::factory(),
            'SKU' => $this->faker->numberBetween(100000000000, 999999999999),
            'unit' => Unit::factory(),
            'status' => $this->faker->randomElement([0, 1]),
        ];
    }
}
