@extends('layouts.app')

@section('styles')
<style>
    /* A4 dimensions for screen preview (portrait only) */
    .print-content {
        background-color: #fff;
        width: 210mm;
        height: auto;
        padding: 10mm;
        box-sizing: border-box;
        margin: 0 auto;
        border: 1px solid #ddd;
        box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
        transition: width 0.3s, height 0.3s;
    }

    /* Ensure the page is responsive for A4 Portrait */
    @media (max-width: 1024px) {
        .print-content {
            width: 100%;
            max-width: 210mm;
            max-height: auto;
        }
    }

    @page {
        size: A4 portrait;
        margin: 0;
    }

    /* Print styles */
    @media print {

        /* Hide non-printable elements */
        .no-print {
            display: none !important;
        }

        /* Hide navbar and sidebar during print */
        .sidebar,
        .navbar {
            display: none !important;
        }

        body,
        html {
            margin: 0 !important;
            padding: 0 !important;
            height: 100%;
            background-color: #fff;
        }

        .print-content {
            margin: 0;
            width: 100%;
            height: auto;
            background-color: #fff;
            box-shadow: none;
            border: none;
            padding: 10mm;
        }

        .print-content,
        .print-content * {
            page-break-inside: avoid;
        }
    }

    table {
        width: 100%;
        border-collapse: collapse;
    }

    table,
    th,
    td {
        border: 1px solid #ddd;
    }

    th,
    td {
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #f4f4f4;
    }

    .report-footer {
        text-align: center;
        font-size: 12px;
        margin-top: 20px;
    }
</style>
@endsection

@section('content')
@include('printable.general.header')

<div class="print-content" id="printContent">
    <h1>Sales Report</h1>
    <p><strong>Date Range:</strong> January 1, 2024 - January 31, 2024</p>

    <!-- Sales Table -->
    <table>
        <thead>
            <tr>
                <th>Item</th>
                <th>Quantity Sold</th>
                <th>Unit Price</th>
                <th>Total Sales</th>
            </tr>
        </thead>
        <tbody>
            <!-- Loop through to create 100 rows of dummy data -->
            @for ($i = 1; $i <= 100; $i++)
                <tr>
                <td>Item {{ $i }}</td>
                <td>{{ rand(10, 100) }}</td>
                <td>${{ number_format(rand(5, 20), 2) }}</td>
                <td>${{ number_format(rand(5, 20) * rand(10, 100), 2) }}</td>
                </tr>
                @endfor
        </tbody>
        <tfoot>
            <tr>
                <th colspan="3">Total</th>
                <th>
                    ${{ number_format(100 * rand(5, 20) * rand(10, 100), 2) }}
                </th>
            </tr>
        </tfoot>
    </table>

    <!-- Footer with additional report info -->
    <div class="report-footer">
        <p>Report generated by: Your Company Name</p>
        <p>Contact: info@company.com</p>
    </div>
</div>
@endsection

@section('scripts')
@endsection